on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build job for npm projects
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm i
      - run: npm run build
      - name: Clone and push build
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git clone --single-branch "https://github.com/mirror12k/mirror12k.github.io.git" "upload_project"
          ls upload_project
          rm -rf upload_project/markovian
          mv dist upload_project/markovian
          git config --global user.email "robot@robot.local"
          git config --global user.name "robot"
          cd upload_project
          git add markovian
          git commit -m 'automated build push!'
          git push "https://x-access-token:$API_TOKEN_GITHUB@github.com/mirror12k/mirror12k.github.io.git"
          git status
